version: '3.3'

services:
   appphp2020igor:
     depends_on:
       - dbigor  
     image: igorfortes/appphp2020:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       - DB_HOST=dbigor
       - DB_USER=root
       - DB_PASSWORD=bob
       - DB_NAME=univille
   dbigor:
     image: mysql:5.7
     restart: always
#     ports:
#       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: bob
       MYSQL_DATABASE: univille
       MYSQL_USER: bob
       MYSQL_PASSWORD: bob